// web -1.0 - react/src/components/Publish/Publish.tsx
import React, { CSSProperties, useEffect, useState } from 'react'
import { Button, Input, message, Upload } from 'antd'


import IconButton from '@mui/material/IconButton';
import PhotoCamera from '@mui/icons-material/PhotoCamera';


import './style.scss'
import {
  PictureOutlined,
  SmileOutlined ,
  LinkOutlined 
} from '@ant-design/icons';
import { getPlatform } from '../../utils';
import { uploadIcon } from '../../service/user';
import axios from 'axios';
import { uploadPost } from '../../service/post';
import { userStore } from '../../store/user';
import { Post } from '@/Model/post';

interface PublishProps {
  textAreaStyle?: CSSProperties | undefined,
  minRows?:number,
  onUploadNewPost:(post:Post)=>void;
}
const baseTextAreaStyle = {
    border:0,
    fontSize:'18px',
    height:'90%',
    fontWeight:500,
    marginBottom:40
}

export default function Publish( props : PublishProps ) {
  const { textAreaStyle , minRows , onUploadNewPost } = props
  const { TextArea } = Input
  const [value, setValue] = useState('')
  const [isWindows, setIsWindows] = useState<boolean>(getPlatform()==='windows')
  const [fileList, setFileList] = useState<File[] >([])
  const [imageUrl, setimageUrl] = useState<string[] | undefined   >()

  
  
  const cancelPic = (index) =>{
    
    if(imageUrl!==undefined) {
      let imageTemp = [...imageUrl]
      imageTemp  = imageTemp.filter((value,i, arr)=> i !== index)
      setimageUrl(()=>imageTemp)

      let fileListTemp = [...fileList];
      fileListTemp = fileListTemp.filter((value,i,arr)=>i !== index)
      setFileList(()=>fileListTemp)

      console.log(imageTemp);
    }
    
  }

  const onDownload = (e) =>{
    let file = e.target.files[0]
    console.log(file,e.target.files);
   
    if (window.FileReader) {    
      var reader = new FileReader();    
      if(file){
        setFileList(()=>[...fileList,file])
        console.log(fileList);

        
          reader.readAsDataURL(file);    
          //监听文件读取结束后事件    
            reader.onloadend = function (e) {

              
              imageUrl!==undefined ?
              // @ts-ignore
                    setimageUrl(()=>[...imageUrl , e.target?.result])
                    :
              // @ts-ignore
                    setimageUrl(()=>[e.target?.result])
              
              
              /* axios({
                  method: 'POST',
                  url: '/upLoadIcon',
                  baseURL: 'http://dandan.ihk.vipnps.vip/',
                  data: param,
                  headers: {
                      'Content-Type': 'multipart/form-data',
                  }
              }).then(res=>{
                console.log(res.data);
              }) */
          }
      };    
   } 
  }

  const onSubmit = (e) =>{
    console.log(fileList,userStore.userInfo?.id,value);
    uploadPost(fileList,String(userStore.userInfo?.id),value).then(res=>{
        if( res.data.msg === '文章上傳成功' ){
            message.info(`${res.data.msg} !`);
            const { msg , postId , postImage } = res.data
            onUploadNewPost( {
              id:postId,
              postImage:postImage,
              introduction:value,
              likeCount:0,
              postDate:new Date(),
              userId:userStore.userInfo?.id
            } );

            setValue('')
            setFileList([])
            setimageUrl([])
            
        }
    })
  }

  return (
    <div className='publish-container' 
    style={{display:'flex',position: 'relative',}}>
        <img 
            style={{width:'40px',height:'40px',borderRadius:'20px'}} 
            src={require('../../assets/icon.png')} 
        />
        <div className='publish-right-container' >
         
          <TextArea 
              value={value}
              onChange={v=>setValue(v.target.value)}
              placeholder="What's happening?" 
              autoSize={{ minRows: minRows!==undefined?minRows:1, maxRows: 10 }}
              bordered={false}
              
              style={{
                ...baseTextAreaStyle
              }}
          />
          <div  style={{width:'100%',height:1,background:"#F4F4F4",marginBottom:15}} />
          
          <div style={{display:imageUrl !== undefined ? 'flex':'none' ,position:'relative',justifyContent:'flex-start',flexDirection:'row',marginBottom:10}}>
              
              
              {
                  /*  上傳的圖片 */
                  imageUrl?.map((item,index)=>{
                    return (
                      <div className='post-pic-container' style={{position:'relative' , width:'auto', height:'auto'}}>
                        <div onClick={()=>cancelPic(index)} style={{position:'absolute',right:0,top:-5,
                        cursor:'pointer',width:20,height:20,borderRadius:10,backgroundColor:"rgb(93,160,241)",color:"#FFFFFF",fontSize:8}} >
                          x
                        </div>
                        <img  src={item} alt="" style={{width:80,height:80,borderRadius:5,objectFit:'cover',marginRight:10}} />
                      </div>
                    )
                  })
              }
          </div>  

          <div className='publish-bottom-container' >
              <label htmlFor="icon-button-file">
                <Input 
                style={{display:'none'}} 
                 accept="image/*" 
                 id="icon-button-file" 
                type="file" 
                onChange={onDownload} />
                <IconButton  
                style={{width:32,height:32,backgroundColor:"rgb(244, 244, 244)",marginRight:10}} 
                color="primary" 
                aria-label="upload picture" 
                component="span">
                  <PhotoCamera />
                </IconButton>

                
              </label>
               
       
            <div style={{display:isWindows?'flex':'none'}}>
              <Button 
              type='default'
              icon={<SmileOutlined />} 
              style={{border:0,backgroundColor:"#F4F4F4",borderRadius:20,marginRight:10}}>
                  emjio
              </Button>
            </div>
            <Button 
            type='default'
            icon={<LinkOutlined />} 
            style={{border:0,backgroundColor:"#F4F4F4",borderRadius:20,marginRight:10}}>
                Link
            </Button>
            <div style={{flex:1,display:'flex',justifyContent: 'flex-end',}}>
              <Button onClick={onSubmit} type='primary' style={{borderRadius:20}} >
                submit
              </Button>
            </div>
          </div>
        </div>
    </div>
  )
}

// web -2.0 - vue3/src/components/Publish.vue
<script setup lang='ts'>
import {defineProps, toRefs, ref, watchEffect, onMounted, CSSProperties, unref} from 'vue';
import {useState} from '@/hooks/useState';
import { FormattedPost, Post } from '@/types/post';
import  { ElMessage, ElMessageBox, ElNotification, UploadFiles, UploadProps, UploadUserFile  } from 'element-plus'
import  { Picture } from '@element-plus/icons-vue'
import { UserInfo } from '@/types/user.js';
import { loadData } from '@/utils/FakePost'
import pubsub from 'pubsub-js'
import { file } from '@babel/types';
import { log } from 'console';
import { uploadPost } from '@/service/post';
import { LocalStorageManager } from '@/utils/localStorage';
import { useUserStore } from '@/store/user';
import { normalUrl } from '@/api/config';
interface PublishProps {
    textAreaStyle?: CSSProperties | undefined,
    minRows?:number,
    onUploadNewPost:(post: FormattedPost,des:string,files:File[])=>void;
    underline?:boolean,
    
}
const props = defineProps<PublishProps>()
const { textAreaStyle , minRows , onUploadNewPost, underline } = toRefs(props)
const { textArea,imageUrl , isWindows,  uploadPicList } = useState({
    textArea :'',
    imageUrl:'',
    isWindows:true,
    //fileList:[] as UploadUserFile[],
    uploadPicList:[] as string[],
})
let fileList :File[] = [];

const userInfo = useUserStore().userInfo
const onSubmit=()=>{
  let post:Post = {
    content: '',
    images: '',
    user_id: LocalStorageManager.getLocalStorageInfo('userInfo')?.id!,
    like: 0,
    comments: 0,
    name: '',
    avatar: '',
    id: -1,
    title: '',
    created_at: ''
  }
  if(textArea.value){
      post.content = textArea.value;
      post.images =  uploadPicList.value[0] 
      if(onUploadNewPost?.value){
        onUploadNewPost.value(post, textArea.value,fileList)
      }
      textArea.value = ''
      uploadPicList.value = [];
      fileList = []
  }
}

const cancelPic=(index)=>{
   uploadPicList.value =  uploadPicList.value.filter((v,i)=>i!==index);
   fileList =  fileList.filter((v,i)=>i!==index);
}

const onChange:UploadProps['onChange'] = async (uploadFIle,uploadFiles)=>{
  fileList.push(uploadFIle.raw as File);
  const url = URL.createObjectURL(uploadFIle.raw!)
  uploadPicList.value.push(url)
}

</script>
<template>
  <div class='publish-container' style="display:flex">
        <img 
         style="width:40px;height:40px;borderRadius:20px" 
            :src="normalUrl +  userInfo?.avatar"
        />
        <div class='publish-right-container' >
           
          <textarea
          class="text-input"
          placeholder="What's happening?"
          :rows="minRows?minRows:3"
          v-model="textArea"
          @keydown.enter="onSubmit"
          />
          <div  style="width:100%;height:1px;background:#F4F4F4;margin-bottom:15px" />
          <div :style="{display:uploadPicList.length !== 0 ? 'flex':'none' ,justifyContent:'flex-start',flexDirection:'row',marginBottom:'10px'}">
              <div @click="cancelPic(index)" :key="index" v-for="(item,index) in uploadPicList" class='post-pic-container' >
                <div  :style="{position:'absolute',right:'0',top:'-5px',
                cursor:'pointer',width:'20px',height:'20px',borderRadius:'10px',backgroundColor:'rgb(93,160,241)',color:'#FFFFFF',fontSize:'8px',textAlign:'center'}" >
                  x
                </div>
                <img  :src="item" alt="" :style="{width:'80px',height:'80px',borderRadius:5,objectFit:'cover',marginRight:10}" />
              </div>
          </div> 
           

          <div class='publish-bottom-container' >
            <div :style="{display:isWindows?'flex':'none'}">
              <el-upload
                v-model:file-list="fileList"
                class="upload-demo"
                multiple
                :auto-upload="false"
                show-file-list
                :on-change="onChange"
              >
                <el-button type='primary' size="large" :icon="Picture" circle style="font-size: 14px;margin-right: 10px;" />
              </el-upload>
              <el-button 
              type='default'
              round
              style="border:0;backgroundColor:#F4F4F4;border-radius:20;margin-right:10px">
                  emjio
              </el-button>
            </div>
            <el-button 
            round
            type='default'
            style="border:0;backgroundColor:#F4F4F4;border-radius:20;margin-right:10px">
                Link
            </el-button >
            <div :style="{flex:1,display:'flex',justifyContent: 'flex-end'}">
              <el-button @click="onSubmit"  type='primary' :style="{borderRadius:20}" round >
                submit
              </el-button>
            </div>
          </div>
        </div>
    </div>
    <div v-if="underline"  
    style="width:100%;border: 0px solid rgb(244, 244, 244);
    border-bottom-width: 0.5px;margin-bottom:0px" />
</template>

<style lang="less" scoped>
::-webkit-scrollbar {
  width: 8px;
  background-color: #f2f2f2;
  cursor: pointer;
}

::-webkit-scrollbar-thumb {
  border-radius: 10px;
  background-color: rgb(222,223,225);
  
}
::-webkit-scrollbar-thumb:hover {
  border-radius: 10px;
  background-color: #CDCDCD;
}

::-webkit-scrollbar-track {
  background-color: #FFFFFF;
}
:deep(.el-upload-list){
  display: none;
}
:deep(.el-textarea){
  border: none !important;
  resize: none !important;
  cursor: pointer;
}
:deep(.el-textarea__inner){
  border: none !important;
  resize: none !important;
}
.publish-container{
        border: 0px solid rgb(238,238,238);
        border-bottom-width: 1px;
        :deep(.el-textarea__inner){
          border: none;
          display: flex;
        }
        padding: 20px;
        padding-top: 10px;
        width: calc(100%-40px);
        
    img{
        margin-right: 7px;
        object-fit: cover;
        box-shadow: 0px 0px 10px #CDCDCD;
    }    
    .publish-right-container{
        flex:1;
        padding-top: 7px;
        .text-input{
          font-weight: 600;
          width:100%;
          border:none;
          font-family: @font-style;
          font-size: 18px;
          color: @fontColor2;
          resize: none;
          outline-color: #FFFFFF;
        }
        .post-pic-container{
          position:relative;
          margin-right: 10px;
        }
    }
    .publish-bottom-container{
        flex:1;
        display:flex
    }
}
</style>
